import transitData from '../../data/demo-transit.json';
import type { CityPack, Explanation, Itinerary, Leg, Place, PlanningConstraints, Stop } from '../models';
import { distanceM, filterCandidates } from './constraints';
import { scorePlace } from './score';
export interface PlanDayInput { cityPack: CityPack; date: string; startPlaceId: string; endPlaceId: string; interests: Record<string, number>; constraints: PlanningConstraints }
export interface TransitLegDisplay { routeName:string; fromStop:string; toStop:string; departure:string; arrival:string; source:string; freshAt:string; transfers?:number }
export function summarizeTransitLeg(leg:Leg):TransitLegDisplay { const row=transitData.find(x=>x.routeRef===leg.routeRef); return {routeName:row?.routeName??leg.routeRef??'Transit',fromStop:row?.fromStop??leg.from,toStop:row?.toStop??leg.to,departure:row?.departure??'unknown',arrival:row?.arrival??'unknown',source:row?.source??'GTFS sample',freshAt:leg.dataFreshAt??row?.freshAt??'unknown',transfers:leg.transfers??row?.transfers??0}; }
function makeItinerary(input:PlanDayInput, sequence:Place[]):Itinerary { const {cityPack,constraints}=input; const start=cityPack.places.find(p=>p.id===input.startPlaceId)??cityPack.places[0]; const end=cityPack.places.find(p=>p.id===input.endPlaceId)??start; const stops:Stop[]=sequence.map((p,i)=>({placeId:p.id,kind:p.category,arrival:`${9+i}:00`,departure:`${10+i}:00`,durationMin:p.durationMin??(p.category==='meal'?60:20)})); const legs:Leg[]=[]; let prev=start,steps=0,walkM=0,transitMin=0,transfers=0; for(const p of sequence.concat(end)){if(p.id===prev.id)continue; const d=distanceM(prev.lat,prev.lon,p.lat,p.lon)*cityPack.rules.walkingEffortMultiplier; const route=cityPack.rules.transitRoutes?.[0]; const transit=d>constraints.maxSingleWalkM; const leg:Leg=transit?{mode:'transit',from:prev.id,to:p.id,distanceM:d,durationMin:Math.max(8,Math.round(d/250)),transfers:route?.transfers??0,routeRef:route?.routeRef,riskFlags:[],dataFreshAt:route?.freshAt}:{mode:'walk',from:prev.id,to:p.id,distanceM:d,durationMin:Math.max(5,Math.round(d/75)),transfers:0,riskFlags:[],dataFreshAt:'2026-09-19'}; legs.push(leg); if(transit){transitMin+=leg.durationMin;transfers+=leg.transfers??0;}else{walkM+=d;steps+=Math.ceil(d/.72);} prev=p;} return {cityId:cityPack.id,date:input.date,stops,legs,totals:{steps,walkM:Math.round(walkM),transitMin,transfers,backtrackM:0},explanations:[],freshness:{sources:sequence.flatMap(p=>p.sourceRefs)}}; }
export function planDay(input:PlanDayInput):Itinerary { const {cityPack,constraints}=input; const start=cityPack.places.find(p=>p.id===input.startPlaceId)??cityPack.places[0]; const candidates=cityPack.places.filter(p=>!['hotel','meal','rest'].includes(p.category)); const filtered=filterCandidates({candidates,cityPack,constraints,from:start}); const explanations:Explanation[]=filtered.excluded.flatMap(x=>x.explanations); const ranked=filtered.included.sort((a,b)=>scorePlace(b,{interests:input.interests,cityPack,constraints}).total-scorePlace(a,{interests:input.interests,cityPack,constraints}).total); const chosen:Place[]=[]; for(const p of ranked){const probe=makeItinerary(input,[...chosen,p]); if(probe.totals.steps<=constraints.maxDailySteps){chosen.push(p);} if(chosen.length>=4)break;} const meal=cityPack.places.find(p=>p.category==='meal'); const rest=cityPack.places.find(p=>p.category==='rest'); const sequence=[...chosen]; if(meal&&constraints.mealWindows.length)sequence.splice(Math.min(2,sequence.length),0,meal); if(rest)sequence.splice(Math.min(3,sequence.length),0,rest); while(sequence.length&&makeItinerary(input,sequence).totals.steps>constraints.maxDailySteps){const index=sequence.map(p=>p.category).lastIndexOf('sight'); if(index<0)break; sequence.splice(index,1);} const itinerary=makeItinerary(input,sequence); for(const p of sequence)if(p.access?.stepFree==='unknown')explanations.push({code:'unknown-access',severity:'warning',placeId:p.id,message:'Accessibility status is unknown; verify on site',sourceRefs:p.sourceRefs}); if(itinerary.totals.steps>constraints.maxDailySteps)explanations.push({code:'over-budget',severity:'error',message:`无法在当前节点组合下满足 ${constraints.maxDailySteps} 步预算`}); itinerary.explanations=explanations; return itinerary; }
export interface ReplaceStopInput extends PlanDayInput { itinerary:Itinerary; lockedPlaceIds:string[]; replacementPlaceId:string }
export function replaceStop(input:ReplaceStopInput):Itinerary { const replacement=input.cityPack.places.find(p=>p.id===input.replacementPlaceId); if(!replacement)throw new Error(`Unknown replacement: ${input.replacementPlaceId}`); const targetIndex=input.itinerary.stops.findIndex(s=>!input.lockedPlaceIds.includes(s.placeId)); if(targetIndex<0)return input.itinerary; const ids=input.itinerary.stops.map(s=>s.placeId); ids[targetIndex]=replacement.id; const places=ids.map(id=>input.cityPack.places.find(p=>p.id===id)).filter(Boolean) as Place[]; return makeItinerary(input,places); }
