import transitData from '../../data/demo-transit.json';
import type { CityPack, Explanation, Itinerary, Leg, Place, PlanningConstraints, Stop } from '../models';
import { distanceM, filterCandidates } from './constraints';
import { scorePlace } from './score';
export interface PlanDayInput { cityPack: CityPack; date: string; startPlaceId: string; endPlaceId: string; interests: Record<string, number>; constraints: PlanningConstraints }
export interface TransitLegDisplay { routeName: string; fromStop: string; toStop: string; departure: string; arrival: string; source: string; freshAt: string; transfers?: number }
export function summarizeTransitLeg(leg: Leg): TransitLegDisplay { const row = transitData.find((x) => x.routeRef === leg.routeRef); return { routeName: row?.routeName ?? leg.routeRef ?? 'Transit', fromStop: row?.fromStop ?? leg.from, toStop: row?.toStop ?? leg.to, departure: '09:30', arrival: `+${leg.durationMin} min`, source: row?.source ?? 'GTFS sample', freshAt: leg.dataFreshAt ?? row?.freshAt ?? 'unknown', transfers: leg.transfers ?? row?.transfers ?? 0 }; }
export function planDay(input: PlanDayInput): Itinerary { const {cityPack,constraints}=input; const start=cityPack.places.find(p=>p.id===input.startPlaceId) ?? cityPack.places[0]; const end=cityPack.places.find(p=>p.id===input.endPlaceId) ?? start; const candidates=cityPack.places.filter(p=>!['hotel','meal','rest'].includes(p.category)); const filtered=filterCandidates({candidates,cityPack,constraints,from:start}); const explanations: Explanation[] = filtered.excluded.flatMap(x=>x.explanations); const chosen=filtered.included.sort((a,b)=>scorePlace(b,{interests:input.interests,cityPack,constraints}).total-scorePlace(a,{interests:input.interests,cityPack,constraints}).total).slice(0,4); const meal=cityPack.places.find(p=>p.category==='meal'); const rest=cityPack.places.find(p=>p.category==='rest'); const sequence: Place[]=[...chosen]; if(meal) sequence.splice(Math.min(2,sequence.length),0,meal); if(rest) sequence.splice(Math.min(3,sequence.length),0,rest); const stops: Stop[] = sequence.map(p=>({placeId:p.id,kind:p.category,durationMin:p.durationMin??(p.category==='meal'?60:20)})); const legs: Leg[]=[]; let prev=start; let walkM=0, steps=0, transitMin=0, transfers=0; for(const p of sequence.concat(end)) { if(p.id===prev.id) continue; const raw=distanceM(prev.lat,prev.lon,p.lat,p.lon); const adjusted=raw*cityPack.rules.walkingEffortMultiplier; const useTransit=adjusted>constraints.maxSingleWalkM; const leg:Leg=useTransit?{mode:'transit',from:prev.id,to:p.id,distanceM:adjusted,durationMin:Math.max(8,Math.round(adjusted/250)),transfers:1,routeRef:cityPack.id==='rome'?'rome-bus-87':'guiyang-metro-1',riskFlags:[],dataFreshAt:'2026-09-19'}:{mode:'walk',from:prev.id,to:p.id,distanceM:adjusted,durationMin:Math.max(5,Math.round(adjusted/75)),transfers:0,riskFlags:[],dataFreshAt:'2026-09-19'}; legs.push(leg); if(leg.mode==='walk'){walkM+=adjusted;steps+=Math.ceil(adjusted/0.72);} else {transitMin+=leg.durationMin;transfers+=leg.transfers??0;} prev=p; }
  if(steps>constraints.maxDailySteps){ explanations.push({code:'over-budget',severity:'warning',message:`预计步数 ${steps} 超过每日上限 ${constraints.maxDailySteps}`}); }
  for(const p of sequence) if(p.access?.stepFree==='unknown') explanations.push({code:'unknown-access',severity:'warning',placeId:p.id,message:'无障碍状态未知，未标记为无障碍',sourceRefs:p.sourceRefs});
  return {cityId:cityPack.id,date:input.date,stops,legs,totals:{steps,walkM:Math.round(walkM),transitMin,transfers,backtrackM:0},explanations,freshness:{sources:sequence.flatMap(p=>p.sourceRefs)}};
}
export interface ReplaceStopInput extends PlanDayInput { itinerary: Itinerary; lockedPlaceIds: string[]; replacementPlaceId: string }
export function replaceStop(input: ReplaceStopInput): Itinerary { const replacement=input.cityPack.places.find(p=>p.id===input.replacementPlaceId); if(!replacement) throw new Error(`Unknown replacement: ${input.replacementPlaceId}`); const stops=input.itinerary.stops.map(s=>input.lockedPlaceIds.includes(s.placeId)?s:{...s,placeId:replacement.id,kind:replacement.category}); return {...input.itinerary,stops}; }
