import { useMemo, useState } from 'react';
import { getCityPack, listCityPacks } from './city-packs/registry';
import { planDay } from './domain/planner/buildItinerary';
import MapView from './features/map/MapView';
import { NarrationCard } from './features/ar/components/NarrationCard';
import { ArPanel } from './features/ar/components/ArPanel';
import { ShareClient } from './features/share/ShareClient';
import { ShareSheet } from './features/share/components/ShareSheet';
import { SosButton } from './features/safety/components/SosButton';
import { EmergencySheet } from './features/safety/components/EmergencySheet';

const cityNames: Record<string,string> = {rome:'罗马',guiyang:'贵阳'};
export default function App(): JSX.Element {
  const [cityId,setCityId]=useState<'rome'|'guiyang'>('rome'); const [steps,setSteps]=useState(7000); const [walk,setWalk]=useState(900); const [wheelchair,setWheelchair]=useState(false); const [version,setVersion]=useState(0);
  const pack=getCityPack(cityId); const itinerary=useMemo(()=>planDay({cityPack:pack,date:'2026-10-03',startPlaceId:`${cityId}-hotel`,endPlaceId:`${cityId}-hotel`,interests:{history:2,culture:2,nature:1,food:1},constraints:{maxDailySteps:steps,maxSingleWalkM:walk,restEveryMin:70,mealWindows:[{type:'lunch',start:'12:00',end:'13:30'}],wheelchairMode:wheelchair}}),[cityId,pack,steps,walk,wheelchair,version]); const first=pack.places.find(p=>p.category==='sight')??pack.places[0]; const heritage=pack.heritageAssets[0];
  return <main className="app-shell"><header className="topbar"><div><p className="eyebrow">AR TRIP HELPER · Android PWA</p><h1>把一天的路线，调整到适合你的节奏。</h1></div><button className="quiet-button" type="button">设置</button></header>
    <nav className="city-tabs" aria-label="城市选择">{listCityPacks().map(item=><button key={item.id} type="button" role="tab" aria-selected={cityId===item.id} className={cityId===item.id?'city-tab active':'city-tab'} onClick={()=>setCityId(item.id as 'rome'|'guiyang')}><span>{cityNames[item.id]??item.name}</span><small>{item.themeTags.slice(0,2).join(' · ')}</small></button>)}</nav>
    <section className="constraint-region" aria-label="行程约束"><div className="section-heading"><div><p className="eyebrow">TODAY'S PARAMETERS</p><h2>规划你的路线</h2></div><span className="status-chip">{cityNames[cityId]}城市包已加载</span></div><div className="form-grid"><label>日期<input type="date" defaultValue="2026-10-03" /></label><label>每日步数上限<input aria-label="每日步数上限" type="number" value={steps} onChange={e=>setSteps(Number(e.target.value)||0)} /></label><label>单段最长步行（米）<input type="number" value={walk} onChange={e=>setWalk(Number(e.target.value)||0)} /></label><label>休息频率<select defaultValue="70"><option value="50">每 50 分钟</option><option value="70">每 70 分钟</option><option value="90">每 90 分钟</option></select></label></div><div className="toggle-row"><label><input aria-label="轮椅或助行器优先" type="checkbox" checked={wheelchair} onChange={e=>setWheelchair(e.target.checked)} /> 轮椅或助行器优先</label><button className="primary-button" type="button" onClick={()=>setVersion(v=>v+1)}>重新规划</button></div></section>
    <div className="content-grid"><section className="timeline-region"><div className="section-heading"><div><p className="eyebrow">{cityNames[cityId]} · OCT 03</p><h2>建议行程</h2></div><span className="freshness">数据更新：刚刚</span></div><p className="budget-note">预计步数 {itinerary.totals.steps.toLocaleString()}，不超过 {steps.toLocaleString()} 的上限</p><ol className="timeline">{itinerary.stops.map((stop,i)=>{const place=pack.places.find(p=>p.id===stop.placeId);return <li key={`${stop.placeId}-${i}`}><span className="time">{stop.arrival??`${9+i}:00`}</span><div><strong>{place?.name??stop.placeId}</strong><p>{stop.kind==='meal'?'用餐窗口':stop.kind==='rest'?'休息节点':`${stop.durationMin??30} 分钟 · 文化兴趣匹配`}</p><span className="pill">{place?.access?.stepFree==='unknown'?'无障碍状态未知':stop.kind==='meal'?'用餐':'路线节点'}</span></div></li>;})}</ol>{itinerary.explanations.length>0&&<ul className="explanation-list">{itinerary.explanations.slice(0,4).map((e,i)=><li key={`${e.code}-${i}`}>{e.message}</li>)}</ul>}</section><MapView itinerary={itinerary}/></div>
    <section className="lower-grid"><article className="dashboard-panel"><p className="eyebrow">EFFORT DASHBOARD</p><div className="metric-row"><div><strong>{itinerary.totals.steps.toLocaleString()}</strong><span>预计步数</span></div><div><strong>{(itinerary.totals.walkM/1000).toFixed(1)} km</strong><span>步行</span></div><div><strong>{itinerary.totals.transfers}</strong><span>换乘</span></div></div><div className="progress-track"><span style={{width:`${Math.min(100,Math.round(itinerary.totals.steps/Math.max(1,steps)*100))}%`}} /></div><p className="muted">预算使用率 · 最长步行段 {walk} 米</p></article><article className="explain-panel"><p className="eyebrow">WHY THIS ROUTE</p><h3>路线解释</h3><ul><li>兴趣标签和城市主题优先。</li><li>长距离步行自动尝试城市包公交数据。</li><li>未知无障碍状态保持为未知，不会宣称可达。</li></ul></article></section>
    <section className="ar-region" aria-label="AR 与解说"><div><p className="eyebrow">ARRIVAL CONTENT</p><h2>{first.name} · 解说与 AR</h2><NarrationCard place={first}/></div><ArPanel asset={heritage} capabilities={{webXr:false,camera:false,deviceOrientation:false}}/></section>
    <section className="safety-share-grid"><ShareSheet tripId={`trip-${cityId}-demo`} createSession={(input)=>ShareClient.createSession(input)}/><div><SosButton tripId={`trip-${cityId}-demo`} emergencyTargets={pack.rules.emergencyTargets} notifyContacts={async()=>undefined}/><EmergencySheet targets={pack.rules.emergencyTargets}/></div></section>
  </main>;
}
